# Generated by Django 6.0.6 on 2026-06-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('ai', 'AI'), ('ecommerce', 'E-commerce'), ('saas', 'SaaS')], default='web', max_length=20)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='Comma-separated list of technologies', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('image_url', models.URLField(blank=True)),
                ('demo', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('color', models.CharField(default='from-blue-500 to-cyan-500', help_text='Tailwind gradient classes', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
